### ISSUE TITLE
Hide on scroll down issue

### ISSUE THREAD

**Issue by AndreiPisica** [Pradeep-selva/react-hide-on-scroll#1]
I am not sure this is an issue, or I am doing something wrong. The hide on scroll down works, but the when you first load the page with the div that you want it to be hidden on scroll down it is already hidden, and it pops up after you scroll a bit down and go up a bit. 
Is there a props that I can set for it to be visible on page load?

**Comment by Pradeep-selva** [comment]
Nope there isnt a prop for that yet. 
The issue will be fixed soon. Feel free to contribute :)
