### ISSUE TITLE
Show on page init for HideOn component

### ISSUE THREAD

**Issue by jbust97** [Pradeep-selva/react-hide-on-scroll#3]
I cannot make the element enclosed in the HideOn component to appear when the page has freshly started. Is there something I can tweak to easily achieve that?

**Comment by Pradeep-selva** [comment]
Hey,
Sorry about that. That was an existing bug. 
However i've fixed it now. Please upgrade to version 1.1.4 of the package, and try it out.

Now the component will appear on fresh start by default, but if you dont want this behaviour you could also set the `showOnPageInit` prop of `HideOn` component to `false`.

- Please check out the [new documentation](https://www.npmjs.com/package/react-hide-on-scroll) (find HideOn component in the API section.)
- Check the [new demo](https://pradeep-selva.github.io/react-hide-on-scroll/)

Let me know if u face any more issues, and if i can close this issue
Thank you for using and feel free to contribute!

**Comment by Pradeep-selva** [comment]
Let me know if i can close this

**Comment by jbust97** [comment]
Works on the new version! thank you
